// AUTO-GENERATED by scripts/gen-illustrations.mjs — AI Madhubani illustrations.
export const ILLUS_MEDIA = {
  "illus-govindadas": {
    "src": "/img/illus-govindadas.jpg",
    "alt": "A Vaishnava poet-saint singing kirtan — illustration for the lyricist Govindadas",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "illus-manbodh": {
    "src": "/img/illus-manbodh.jpg",
    "alt": "A poet reciting the Krishna story — illustration for Manbodh’s Haribans",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  }
} as const;
