// AUTO-GENERATED by scripts/gen-covers.mjs — original designed cover art.
export const GEN_MEDIA = {
  "tile-gajendra-narayan-singh": {
    "src": "/img/tile-gajendra-narayan-singh.png",
    "alt": "Gajendra Narayan Singh — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-lakshman-jha": {
    "src": "/img/tile-lakshman-jha.png",
    "alt": "Lakshman Jha — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-maitreyi": {
    "src": "/img/tile-maitreyi.png",
    "alt": "Maitreyi — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-pakshadhara-mishra": {
    "src": "/img/tile-pakshadhara-mishra.png",
    "alt": "Pakshadhara Mishra — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-rameshwar-singh": {
    "src": "/img/tile-rameshwar-singh.png",
    "alt": "Rameshwar Singh — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-santosh-kumar-das": {
    "src": "/img/tile-santosh-kumar-das.png",
    "alt": "Santosh Kumar Das — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-shiva-simha-singh": {
    "src": "/img/tile-shiva-simha-singh.png",
    "alt": "Shiva Simha Singh — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-surendra-jha-suman": {
    "src": "/img/tile-surendra-jha-suman.png",
    "alt": "Surendra Jha 'Suman — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-bisfi-vidyapati-dih": {
    "src": "/img/tile-bisfi-vidyapati-dih.png",
    "alt": "Bisfi Vidyapati Dih — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-dhanushadham": {
    "src": "/img/tile-dhanushadham.png",
    "alt": "Dhanushadham — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-jaleshwar-mahadev": {
    "src": "/img/tile-jaleshwar-mahadev.png",
    "alt": "Jaleshwar Mahadev Temple — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-kandaha-surya-mandir": {
    "src": "/img/tile-kandaha-surya-mandir.png",
    "alt": "Kandaha Surya Mandir — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-salahesh-fulbari": {
    "src": "/img/tile-salahesh-fulbari.png",
    "alt": "Salahesh Fulbari — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-saurath-sabha": {
    "src": "/img/tile-saurath-sabha.png",
    "alt": "Saurath Sabha Gachhi — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-ahiyari": {
    "src": "/img/tile-ahiyari.png",
    "alt": "Ahiyari — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-kariyan": {
    "src": "/img/tile-kariyan.png",
    "alt": "Kariyan — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-lohna": {
    "src": "/img/tile-lohna.png",
    "alt": "Lohna — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-mangrauni": {
    "src": "/img/tile-mangrauni.png",
    "alt": "Mangrauni — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-tarauni": {
    "src": "/img/tile-tarauni.png",
    "alt": "Tarauni — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-biriya-tarkari": {
    "src": "/img/tile-biriya-tarkari.png",
    "alt": "Biriya ke Tarkari — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-kasar": {
    "src": "/img/tile-kasar.png",
    "alt": "Kasar — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-maithil-maus": {
    "src": "/img/tile-maithil-maus.png",
    "alt": "Maithil Maus — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-oal-suran": {
    "src": "/img/tile-oal-suran.png",
    "alt": "Oal (Suran) ke Tarkari — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-pidukiya": {
    "src": "/img/tile-pidukiya.png",
    "alt": "Pidukiya — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-rasiao": {
    "src": "/img/tile-rasiao.png",
    "alt": "Rasiao — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-sinki": {
    "src": "/img/tile-sinki.png",
    "alt": "Sinki — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-tisi-chutney": {
    "src": "/img/tile-tisi-chutney.png",
    "alt": "Tisi ke Chutney — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-aripan": {
    "src": "/img/tile-aripan.png",
    "alt": "Aripan — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-bamboo-craft": {
    "src": "/img/tile-bamboo-craft.png",
    "alt": "Bamboo Craft — Daura, Soop & Changera — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-lac-bangles": {
    "src": "/img/tile-lac-bangles.png",
    "alt": "Lac Bangles (Lakheri Craft) — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-moonj-basketry": {
    "src": "/img/tile-moonj-basketry.png",
    "alt": "Moonj-Grass Coiled Basketry — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-sama-chakeva-clay": {
    "src": "/img/tile-sama-chakeva-clay.png",
    "alt": "Sama-Chakeva Clay Figurines — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-darbhanga-raj": {
    "src": "/img/tile-darbhanga-raj.png",
    "alt": "The Darbhanga Raj (Khandavala Dynasty) — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-karnat-dynasty": {
    "src": "/img/tile-karnat-dynasty.png",
    "alt": "The Karnat Dynasty of Mithila — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-modern-mithila-statehood": {
    "src": "/img/tile-modern-mithila-statehood.png",
    "alt": "The Making of Modern Mithila and the Statehood Movement — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-oiniwar-dynasty": {
    "src": "/img/tile-oiniwar-dynasty.png",
    "alt": "The Oiniwar (Sugauna) Dynasty — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-panji-prabandh": {
    "src": "/img/tile-panji-prabandh.png",
    "alt": "The Panji Prabandh — Mithila's Genealogical Archive — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-videha-kingdom-janaka": {
    "src": "/img/tile-videha-kingdom-janaka.png",
    "alt": "The Videha Kingdom and the Janaka Kings — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  }
} as const;
