// AUTO-GENERATED by scripts/gen-ai-images.mjs — AI illustrations (Pollinations/FLUX), Madhubani style.
export const AI_MEDIA = {
  "ai-bharati-mishra": {
    "src": "/img/ai-bharati-mishra.jpg",
    "alt": "Bharati (Ubhaya Bharati) — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-kirti-azad": {
    "src": "/img/ai-kirti-azad.jpg",
    "alt": "Kirti Azad — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-nitin-chandra": {
    "src": "/img/ai-nitin-chandra.jpg",
    "alt": "Nitin Chandra — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-ahilya-asthan": {
    "src": "/img/ai-ahilya-asthan.jpg",
    "alt": "Ahilya Asthan, Kamtaul — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-gautam-asthan": {
    "src": "/img/ai-gautam-asthan.jpg",
    "alt": "Gautam Asthan — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-haleshwar-sthan": {
    "src": "/img/ai-haleshwar-sthan.jpg",
    "alt": "Haleshwar Sthan — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-hariharnath": {
    "src": "/img/ai-hariharnath.jpg",
    "alt": "Hariharnath, Sonepur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-kusheshwar-asthan": {
    "src": "/img/ai-kusheshwar-asthan.jpg",
    "alt": "Kusheshwar Asthan — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-andhratharhi": {
    "src": "/img/ai-andhratharhi.jpg",
    "alt": "Andhra Tharhi — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-bahadurpur": {
    "src": "/img/ai-bahadurpur.jpg",
    "alt": "Bahadurpur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-benipatti": {
    "src": "/img/ai-benipatti.jpg",
    "alt": "Benipatti — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-brahmpur": {
    "src": "/img/ai-brahmpur.jpg",
    "alt": "Brahmpur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-dhalkebar": {
    "src": "/img/ai-dhalkebar.jpg",
    "alt": "Dhalkebar — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-gaur": {
    "src": "/img/ai-gaur.jpg",
    "alt": "Gaur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-ghoghardiha": {
    "src": "/img/ai-ghoghardiha.jpg",
    "alt": "Ghoghardiha — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-hayaghat": {
    "src": "/img/ai-hayaghat.jpg",
    "alt": "Hayaghat — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-jaleshwar": {
    "src": "/img/ai-jaleshwar.jpg",
    "alt": "Jaleshwar — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-kamtaul": {
    "src": "/img/ai-kamtaul.jpg",
    "alt": "Kamtaul — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-madhepur": {
    "src": "/img/ai-madhepur.jpg",
    "alt": "Madhepur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-madhwapur": {
    "src": "/img/ai-madhwapur.jpg",
    "alt": "Madhwapur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-pandaul": {
    "src": "/img/ai-pandaul.jpg",
    "alt": "Pandaul — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-phulhar": {
    "src": "/img/ai-phulhar.jpg",
    "alt": "Phulhar — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-phulparas": {
    "src": "/img/ai-phulparas.jpg",
    "alt": "Phulparas — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-khatwa": {
    "src": "/img/ai-khatwa.jpg",
    "alt": "Khatwa Appliqué — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-mithila-masks": {
    "src": "/img/ai-mithila-masks.jpg",
    "alt": "Mithila Masks — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-sujani": {
    "src": "/img/ai-sujani.jpg",
    "alt": "Sujani Embroidery — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-mundan": {
    "src": "/img/ai-mundan.jpg",
    "alt": "Mundan — the first haircut — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-panji-system": {
    "src": "/img/ai-panji-system.jpg",
    "alt": "The Panji genealogies — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-shradh": {
    "src": "/img/ai-shradh.jpg",
    "alt": "Antyeshti & Shraddha — the last rites — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-sohar-chhathi": {
    "src": "/img/ai-sohar-chhathi.jpg",
    "alt": "Sohar & Chhathi — welcoming a child — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-pindaruch": {
    "src": "/img/ai-pindaruch.jpg",
    "alt": "Pindaruch — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-rajnagar": {
    "src": "/img/ai-rajnagar.jpg",
    "alt": "Rajnagar — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-rasidpur": {
    "src": "/img/ai-rasidpur.jpg",
    "alt": "Rasidpur — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-sakri": {
    "src": "/img/ai-sakri.jpg",
    "alt": "Sakri — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-sarisab-pahi": {
    "src": "/img/ai-sarisab-pahi.jpg",
    "alt": "Sarisab-Pahi — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-saurath": {
    "src": "/img/ai-saurath.jpg",
    "alt": "Saurath — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-simaria": {
    "src": "/img/ai-simaria.jpg",
    "alt": "Simaria — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-jur-sital": {
    "src": "/img/ai-jur-sital.jpg",
    "alt": "Jur Sital — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-aloo-bhujia": {
    "src": "/img/ai-aloo-bhujia.jpg",
    "alt": "Aloo Bhujia — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-gehuma-bairiya": {
    "src": "/img/ai-gehuma-bairiya.jpg",
    "alt": "Gehuma Bairiya — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-siswar": {
    "src": "/img/ai-siswar.jpg",
    "alt": "Siswar — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-gajendra-narayan-singh": {
    "src": "/img/ai-gajendra-narayan-singh.jpg",
    "alt": "Gajendra Narayan Singh — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-lakshman-jha": {
    "src": "/img/ai-lakshman-jha.jpg",
    "alt": "Lakshman Jha — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-maitreyi": {
    "src": "/img/ai-maitreyi.jpg",
    "alt": "Maitreyi — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-pakshadhara-mishra": {
    "src": "/img/ai-pakshadhara-mishra.jpg",
    "alt": "Pakshadhara Mishra — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-rameshwar-singh": {
    "src": "/img/ai-rameshwar-singh.jpg",
    "alt": "Rameshwar Singh — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-santosh-kumar-das": {
    "src": "/img/ai-santosh-kumar-das.jpg",
    "alt": "Santosh Kumar Das — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-shiva-simha-singh": {
    "src": "/img/ai-shiva-simha-singh.jpg",
    "alt": "Shiva Simha Singh — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-surendra-jha-suman": {
    "src": "/img/ai-surendra-jha-suman.jpg",
    "alt": "Surendra Jha 'Suman — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-bisfi-vidyapati-dih": {
    "src": "/img/ai-bisfi-vidyapati-dih.jpg",
    "alt": "Bisfi Vidyapati Dih — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-dhanushadham": {
    "src": "/img/ai-dhanushadham.jpg",
    "alt": "Dhanushadham — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-jaleshwar-mahadev": {
    "src": "/img/ai-jaleshwar-mahadev.jpg",
    "alt": "Jaleshwar Mahadev Temple — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-kandaha-surya-mandir": {
    "src": "/img/ai-kandaha-surya-mandir.jpg",
    "alt": "Kandaha Surya Mandir — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-salahesh-fulbari": {
    "src": "/img/ai-salahesh-fulbari.jpg",
    "alt": "Salahesh Fulbari — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-saurath-sabha": {
    "src": "/img/ai-saurath-sabha.jpg",
    "alt": "Saurath Sabha Gachhi — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-ahiyari": {
    "src": "/img/ai-ahiyari.jpg",
    "alt": "Ahiyari — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-kariyan": {
    "src": "/img/ai-kariyan.jpg",
    "alt": "Kariyan — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-lohna": {
    "src": "/img/ai-lohna.jpg",
    "alt": "Lohna — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-mangrauni": {
    "src": "/img/ai-mangrauni.jpg",
    "alt": "Mangrauni — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-tarauni": {
    "src": "/img/ai-tarauni.jpg",
    "alt": "Tarauni — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-biriya-tarkari": {
    "src": "/img/ai-biriya-tarkari.jpg",
    "alt": "Biriya ke Tarkari — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-kasar": {
    "src": "/img/ai-kasar.jpg",
    "alt": "Kasar — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-maithil-maus": {
    "src": "/img/ai-maithil-maus.jpg",
    "alt": "Maithil Maus — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-oal-suran": {
    "src": "/img/ai-oal-suran.jpg",
    "alt": "Oal (Suran) ke Tarkari — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-pidukiya": {
    "src": "/img/ai-pidukiya.jpg",
    "alt": "Pidukiya — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-rasiao": {
    "src": "/img/ai-rasiao.jpg",
    "alt": "Rasiao — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-sinki": {
    "src": "/img/ai-sinki.jpg",
    "alt": "Sinki — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-tisi-chutney": {
    "src": "/img/ai-tisi-chutney.jpg",
    "alt": "Tisi ke Chutney — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-aripan": {
    "src": "/img/ai-aripan.jpg",
    "alt": "Aripan — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-bamboo-craft": {
    "src": "/img/ai-bamboo-craft.jpg",
    "alt": "Bamboo Craft — Daura, Soop & Changera — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-lac-bangles": {
    "src": "/img/ai-lac-bangles.jpg",
    "alt": "Lac Bangles (Lakheri Craft) — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-moonj-basketry": {
    "src": "/img/ai-moonj-basketry.jpg",
    "alt": "Moonj-Grass Coiled Basketry — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-sama-chakeva-clay": {
    "src": "/img/ai-sama-chakeva-clay.jpg",
    "alt": "Sama-Chakeva Clay Figurines — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-darbhanga-raj": {
    "src": "/img/ai-darbhanga-raj.jpg",
    "alt": "The Darbhanga Raj (Khandavala Dynasty) — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-karnat-dynasty": {
    "src": "/img/ai-karnat-dynasty.jpg",
    "alt": "The Karnat Dynasty of Mithila — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-modern-mithila-statehood": {
    "src": "/img/ai-modern-mithila-statehood.jpg",
    "alt": "The Making of Modern Mithila and the Statehood Movement — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-oiniwar-dynasty": {
    "src": "/img/ai-oiniwar-dynasty.jpg",
    "alt": "The Oiniwar (Sugauna) Dynasty — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-panji-prabandh": {
    "src": "/img/ai-panji-prabandh.jpg",
    "alt": "The Panji Prabandh — Mithila's Genealogical Archive — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  },
  "ai-videha-kingdom-janaka": {
    "src": "/img/ai-videha-kingdom-janaka.jpg",
    "alt": "The Videha Kingdom and the Janaka Kings — AI-generated illustration in the Mithila (Madhubani) style",
    "credit": {
      "source": "AI illustration (Pollinations · FLUX)",
      "sourceUrl": "https://pollinations.ai",
      "author": "Generated in Madhubani style",
      "license": "CC0"
    },
    "status": "cleared"
  }
} as const;
