// AUTO-GENERATED by scripts/gen-covers.mjs — original designed cover art.
export const GEN_MEDIA = {
  "tile-bharati-mishra": {
    "src": "/img/tile-bharati-mishra.png",
    "alt": "Bharati (Ubhaya Bharati) — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-kirti-azad": {
    "src": "/img/tile-kirti-azad.png",
    "alt": "Kirti Azad — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-nitin-chandra": {
    "src": "/img/tile-nitin-chandra.png",
    "alt": "Nitin Chandra — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-ahilya-asthan": {
    "src": "/img/tile-ahilya-asthan.png",
    "alt": "Ahilya Asthan, Kamtaul — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-gautam-asthan": {
    "src": "/img/tile-gautam-asthan.png",
    "alt": "Gautam Asthan — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-haleshwar-sthan": {
    "src": "/img/tile-haleshwar-sthan.png",
    "alt": "Haleshwar Sthan — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-hariharnath": {
    "src": "/img/tile-hariharnath.png",
    "alt": "Hariharnath, Sonepur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-kusheshwar-asthan": {
    "src": "/img/tile-kusheshwar-asthan.png",
    "alt": "Kusheshwar Asthan — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-andhratharhi": {
    "src": "/img/tile-andhratharhi.png",
    "alt": "Andhra Tharhi — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-bahadurpur": {
    "src": "/img/tile-bahadurpur.png",
    "alt": "Bahadurpur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-benipatti": {
    "src": "/img/tile-benipatti.png",
    "alt": "Benipatti — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-brahmpur": {
    "src": "/img/tile-brahmpur.png",
    "alt": "Brahmpur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-dhalkebar": {
    "src": "/img/tile-dhalkebar.png",
    "alt": "Dhalkebar — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-gaur": {
    "src": "/img/tile-gaur.png",
    "alt": "Gaur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-ghoghardiha": {
    "src": "/img/tile-ghoghardiha.png",
    "alt": "Ghoghardiha — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-hayaghat": {
    "src": "/img/tile-hayaghat.png",
    "alt": "Hayaghat — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-jaleshwar": {
    "src": "/img/tile-jaleshwar.png",
    "alt": "Jaleshwar — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-kamtaul": {
    "src": "/img/tile-kamtaul.png",
    "alt": "Kamtaul — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-madhepur": {
    "src": "/img/tile-madhepur.png",
    "alt": "Madhepur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-madhwapur": {
    "src": "/img/tile-madhwapur.png",
    "alt": "Madhwapur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-pandaul": {
    "src": "/img/tile-pandaul.png",
    "alt": "Pandaul — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-phulhar": {
    "src": "/img/tile-phulhar.png",
    "alt": "Phulhar — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-phulparas": {
    "src": "/img/tile-phulparas.png",
    "alt": "Phulparas — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-pindaruch": {
    "src": "/img/tile-pindaruch.png",
    "alt": "Pindaruch — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-rajnagar": {
    "src": "/img/tile-rajnagar.png",
    "alt": "Rajnagar — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-rasidpur": {
    "src": "/img/tile-rasidpur.png",
    "alt": "Rasidpur — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-sakri": {
    "src": "/img/tile-sakri.png",
    "alt": "Sakri — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-sarisab-pahi": {
    "src": "/img/tile-sarisab-pahi.png",
    "alt": "Sarisab-Pahi — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-saurath": {
    "src": "/img/tile-saurath.png",
    "alt": "Saurath — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-simaria": {
    "src": "/img/tile-simaria.png",
    "alt": "Simaria — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-jur-sital": {
    "src": "/img/tile-jur-sital.png",
    "alt": "Jur Sital — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-aloo-bhujia": {
    "src": "/img/tile-aloo-bhujia.png",
    "alt": "Aloo Bhujia — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-khatwa": {
    "src": "/img/tile-khatwa.png",
    "alt": "Khatwa Appliqué — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-mithila-masks": {
    "src": "/img/tile-mithila-masks.png",
    "alt": "Mithila Masks — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-sujani": {
    "src": "/img/tile-sujani.png",
    "alt": "Sujani Embroidery — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-mundan": {
    "src": "/img/tile-mundan.png",
    "alt": "Mundan — the first haircut — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-panji-system": {
    "src": "/img/tile-panji-system.png",
    "alt": "The Panji genealogies — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-shradh": {
    "src": "/img/tile-shradh.png",
    "alt": "Antyeshti & Shraddha — the last rites — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  },
  "tile-sohar-chhathi": {
    "src": "/img/tile-sohar-chhathi.png",
    "alt": "Sohar & Chhathi — welcoming a child — illustrated cover in the Mithila style",
    "credit": {
      "source": "Original artwork — Mithila Encyclopedia",
      "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Madhubani_paintings",
      "license": "CC-BY-SA-4.0"
    },
    "status": "cleared"
  }
} as const;
